# Generated by Django 5.1 on 2024-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=150)),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('projectHeadName', models.CharField(max_length=100)),
                ('teamMemberName', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
