# Generated by Django 5.1 on 2024-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_report_duedate_remove_report_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportfile',
            field=models.CharField(max_length=7000),
        ),
    ]
