# Generated by Django 5.1 on 2024-08-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
